version: 2.1

orbs:
  lambda: dosomething/lambda@0.0.4
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test


workflows:
  main:
    jobs:
      - build-and-test
      - lambda/deploy:
          app: co-covid-csv-filter
          working_directory: covid-csv-filter
          requires:
            - build-and-test
          # filters:
            # branches:
              # only:
                # - master

